<?php
/**
 * @file
 * Provides integration with Mailgun's email sending API.
 */

use Mailgun\Mailgun;

/**
 * Implements hook_autoload_info().
 */
function mailgun_autoload_info() {
  return array(
    'MailgunMailSystem' => 'includes/mailgun_mail_system.class.inc',
  );
}

/**
 * Implements hook_config_info().
 */
function mailgun_config_info() {
  $prefixes['mailgun.settings'] = array(
    'label' => t('Mailgun settings'),
    'group' => t('Configuration'),
  );
  return $prefixes;
}

/**
 * Implements hook_menu().
 */
function mailgun_menu() {
  $items = array();

  $items['admin/config/services/mailgun'] = array(
    'title' => 'Mailgun',
    'description' => 'Configure Mailgun settings.',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('mailgun_admin_settings'),
    'access arguments' => array('administer mailgun'),
    'file' => 'mailgun.admin.inc',
  );
  $items['admin/config/services/mailgun/settings'] = array(
    'title' => 'Settings',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 0,
  );
  $items['admin/config/services/mailgun/test'] = array(
    'title' => 'Send test email',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('mailgun_test_form'),
    'access arguments' => array('administer mailgun'),
    'description' => 'Send a test e-mail using the Mailgun API.',
    'file' => 'mailgun.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function mailgun_permission() {
  return array(
    'administer mailgun' => array(
      'title' => t('Administer Mailgun'),
      'description' => t('Perform administration tasks for the Mailgun e-mail sending service.'),
      'restrict access' => TRUE,
    ),
  );
}

/**
 * Implements hook_theme().
 */
function mailgun_theme($existing, $type, $theme, $path) {
  return array(
    'mailgun_message' => array(
      'variables' => array(
        'subject' => NULL,
        'body' => NULL,
        'message' => array(),
      ),
      'template' => 'mailgun-message',
      'path' => backdrop_get_path('module', 'mailgun') . '/templates',
      'mail theme' => TRUE,
    ),
  );
}

/**
 * Implements hook_cron_queue_info().
 */
function mailgun_cron_queue_info() {
  $queues = array();
  $queues['mailgun_queue'] = array(
    'worker callback' => 'mailgun_send',
    'time' => 60,
  );
  return $queues;
}

/**
 * Implements hook_mail().
 */
function mailgun_mail($key, &$message, $params) {
  switch ($key) {
    case 'test':
      $message['subject'] = t('Mailgun test email');
      $message['body'] = $params['message'];
      if ($params['attachment']) {
        $message['params']['attachments'] = array(backdrop_realpath('core/themes/basis/images/drop-lounging.png'));
      }
      break;
  }
}

/**
 * Get the Mailgun client to access Mailgun's endpoints.
 *
 * @param string $key
 *   The Mailgun API key. Leave empty to use the API key saved in database.
 *
 * @return \Mailgun\Mailgun|FALSE
 *   Mailgun object or FALSE if Mailgun settings are not correct.
 */
function mailgun_get_client($key = '', $endpoint = '') {
  // Check if the Mailgun PHP library is installed.
  if (!mailgun_check_library()) {
    watchdog('mailgun', 'Mailgun client initialization failed: Unable to load the Mailgun PHP library.', array(), WATCHDOG_ERROR);
    return FALSE;
  }

  $key = (empty($key)) ? config_get('mailgun.settings', 'api_key') : $key;
  if (empty($key)) {
    watchdog('mailgun', 'Mailgun client initialization failed: Missing API key.', array(), WATCHDOG_ERROR);
    return FALSE;
  }

  $endpoint = empty($endpoint) ? config_get('mailgun.settings', 'api_endpoint') : $endpoint;
  if (empty($endpoint)) {
    watchdog('mailgun', 'Mailgun client initialization failed: Missing API endpoint.', array(), WATCHDOG_ERROR);
    return FALSE;
  }

  return Mailgun::create($key, $endpoint);
}

/**
 * Detect if Mailgun library is installed.
 *
 * @return bool
 *   TRUE if library is installed, FALSE otherwise.
 */
function mailgun_check_library() {
  return class_exists('\Mailgun\Mailgun');
}

/**
 * Check if Mailgun API settings are configured.
 *
 * @return bool
 *   TRUE if api settings are configured, FALSE otherwise.
 */
function mailgun_check_api_settings() {
  $config = config('mailgun.settings');
  return !empty($config->get('api_key')) && !empty($config->get('domain'));
}

/**
 * Prepares variables for mailgun-message.tpl.php.
 *
 * Adds id/module/key-specific hook suggestions.
 * For example, user password reset mail will have the following suggestions:
 *  - mailgun_message__user_password_reset;
 *  - mailgun_message__password_reset;
 *  - mailgun_message__user.
 *
 * @see templates/mailgun-message.tpl.php
 */
function template_preprocess_mailgun_message(&$variables) {
  $variables['theme_hook_suggestions'][] = 'mailgun_message__' . $variables['message']['id'];
  $variables['theme_hook_suggestions'][] = 'mailgun_message__' . $variables['message']['key'];
  $variables['theme_hook_suggestions'][] = 'mailgun_message__' . $variables['message']['module'];
}

/**
 * Send an e-mail using the Mailgun API.
 *
 * @param array $mailgun_message
 *   A Mailgun message array. Contains the following keys:
 *   - from: The e-mail addressthe message will be sent from.
 *   - to: The e-mail addressthe message will be sent to.
 *   - subject: The subject of the message.
 *   - text: The plain-text version of the message. Processed using
 *    backdrop_html_to_text().
 *   - html: The original message content. May contain HTML tags.
 *   - cc: One or more carbon copy recipients. If multiple, separate with
 *    commas.
 *   - bcc: One or more blind carbon copy recipients. If multiple, separate
 *    with commas.
 *   - o:tag: An array containing the tags to add to the message.
 *    See: https://documentation.mailgun.com/user_manual.html#tagging.
 *   - o:campaign: The campaign ID this message belongs to.
 *    https://documentation.mailgun.com/user_manual.html#um-campaign-analytics
 *   - o:deliverytime: Desired time of delivery. Messages can be scheduled for
 *    a maximum of 3 days in the future.
 *    See: https://documentation.mailgun.com/api-intro.html#date-format.
 *   - o:dkim: Boolean indicating whether or not to enable DKIM signatures on
 *    per-message basis.
 *   - o:testmode: Boolean indicating whether or not to enable test mode.
 *    See: https://documentation.mailgun.com/user_manual.html#manual-testmode.
 *   - o:tracking: Boolean indicating whether or not to toggle tracking on a
 *    per-message basis.
 *    See: https://documentation.mailgun.com/user_manual.html#tracking-messages.
 *   - o:tracking-clicks: Boolean or string "htmlonly" indicating whether or
 *    not to toggle clicks tracking on a per-message basis. Has higher
 *    priority than domain-level setting.
 *   - o:tracking-opens: Boolean indicating whether or not to toggle clicks
 *    tracking on a per-message basis. Has higher priority than domain-level
 *    setting.
 *   - h:X-My-Header: h: prefix followed by an arbitrary value allows to append
 *    a custom MIME header to the message (X-My-Header in this case).
 *    For example, h:Reply-To to specify Reply-To address.
 *   - v:my-var: v: prefix followed by an arbitrary name allows to attach a
 *    custom JSON data to the message.
 *    See: https://documentation.mailgun.com/user_manual.html#manual-customdata.
 *
 * @return bool
 *   TRUE if the mail was successfully accepted, FALSE otherwise.
 */
function mailgun_send(array $mailgun_message) {
  $client = mailgun_get_client();
  if (!$client) {
    return FALSE;
  }
  $config = config('mailgun.settings');

  // Test mode. Mailgun will accept the message but will not send it.
  if ($config->get('test_mode')) {
    $mailgun_message['o:testmode'] = 'yes';
  }

  // Merge the $mailgun_message array with options.
  $mailgun_message += $mailgun_message['params'];
  unset($mailgun_message['params']);

  if ($config->get('domain', '_sender') === '_sender') {
    // Extract the domain from the sender's email address.
    // Use regular expression to check since it could be either a plain email
    // address or in the form "Name <example@example.com>".
    $tokens = (preg_match('/^\s*(.+?)\s*<\s*([^>]+)\s*>$/', $mailgun_message['from'], $matches) === 1) ? explode('@', $matches[2]) : explode('@', $mailgun_message['from']);
    $mail_domain = array_pop($tokens);

    // Retrieve a list of available domains first.
    $domains = array();
    try {
      $result = $client->domains()->index();
      if (!empty($result)) {
        if ($result->getTotalCount() > 100) {
          $result = $client->domains()->index($result->getTotalCount());
        }
        foreach ($result->getDomains() as $domain) {
          $domains[$domain->getName()] = $domain->getName();
        }
      }
      else {
        watchdog('mailgun', 'Could not retrieve domain list.', array(), WATCHDOG_ERROR);
      }
    }
    catch (Exception $e) {
      watchdog('mailgun', 'An exception occurred while retrieving domains. @code: @message', array(
        '@code' => $e->getCode(),
        '@message' => $e->getMessage(),
      ), WATCHDOG_ERROR);
    }

    if (empty($domains)) {
      // No domain available.
      // Although this shouldn't happen, doesn't hurt to check.
      return FALSE;
    }

    // Now, we need to get the working domain. This is generally the domain the
    // From address is on or the root domain of it.
    $working_domain = '';
    if (in_array($mail_domain, $domains, TRUE)) {
      // Great. Found it.
      $working_domain = $mail_domain;
    }
    else {
      // Oops. No match. Perhaps it's a subdomain instead.
      foreach ($domains as $domain) {
        if (strpos($domain, $mail_domain) !== FALSE) {
          // Got it.
          $working_domain = $domain;
          break;
        }
      }
    }

    // There is a chance that the user is attempting to send from an email
    // address that's on a domain not yet added to the Mailgun account.
    // In that case, abort sending and report error.
    if (empty($working_domain)) {
      watchdog('mailgun', 'Unable to locate a working domain for From address %mail. Aborting sending.', array(
        '%mail' => $mailgun_message['from'],
      ), WATCHDOG_ERROR);
      return FALSE;
    }
  }
  else {
    $working_domain = $config->get('domain');
  }

  // Send message with attachments.
  if (!empty($mailgun_message['attachment'])) {
    foreach ($mailgun_message['attachment'] as &$attachment) {
      // Ignore array constructions. Not sure what values can be here.
      if (is_array($attachment)) {
        continue;
      }
      $attachment = array('filePath' => $attachment);
    }
  }

  try {
    $result = $client->messages()->send($working_domain, $mailgun_message);

    if (!empty($result)) {
      if ($config->get('log_emails')) {
        watchdog('mailgun', 'Successfully sent message from %from to %to. %message.', array(
          '%from' => $mailgun_message['from'],
          '%to' => $mailgun_message['to'],
          '%message' => $result->getMessage(),
        ));
      }
      return TRUE;
    }
    else {
      watchdog('mailgun', 'Failed to send message from %from to %to. %message.', array(
        '%from' => $mailgun_message['from'],
        '%to' => $mailgun_message['to'],
        '%message' => $result->getMessage(),
      ), WATCHDOG_ERROR);
      return FALSE;
    }
  }
  catch (Exception $e) {
    watchdog('mailgun', 'Exception occurred while trying to send test email from %from to %to. @code: @message.', array(
      '%from' => $mailgun_message['from'],
      '%to' => $mailgun_message['to'],
      '@code' => $e->getCode(),
      '@message' => $e->getMessage(),
    ));
    return FALSE;
  }
}
